---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: db2-privileges-cluster-role
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - db2-privileges
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: db2-privileges-cluster-role-binding
roleRef:
  kind: ClusterRole
  name: db2-privileges-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  namespace: stock-trader-data