apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: db2-privileges
spec:
  privileged: false
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - 'SYS_RESOURCE'
  - 'IPC_OWNER'
  - 'SYS_NICE'
  hostIPC: true
  hostNetwork: false
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
