apiVersion: batch/v1
kind: Job
metadata:
  name: create-database-schema
spec:
  template:
    spec:
      containers:
      - name: create-database-schema
        image: store/ibmcorp/db2_developer_c:11.1.3.3a-x86_64
        command: [ "/bin/sh","-c","/scripts/db2-setup.sh" ]
        volumeMounts:
        - name: db2-createschema
          mountPath: /scripts
        securityContext:
          capabilities:
            add: ["SYS_RESOURCE", "IPC_OWNER", "SYS_NICE"]
        env:
        - name: LICENSE
          value: "accept"
        - name: DB2INSTANCE
          value: db2inst1
        - name: DB2INST1_PASSWORD
          valueFrom:
            secretKeyRef:
              name: stocktrade-ibm-db2oltp-dev
              key: password
        - name: DB2_SERVICE_NAME
          value: stocktrade-ibm-db2oltp-dev
        - name: DBNAME
          value: strader
      restartPolicy: Never
      volumes:
      - name: db2-createschema
        configMap:
          name: db2-createschema
          defaultMode: 0744
  backoffLimit: 1
---
apiVersion: v1
data:
  db2-setup.sh: |
    #!/bin/sh
    export SETUPDIR=/var/db2_setup
    source ${SETUPDIR?}/include/db2_constants
    source ${SETUPDIR?}/include/db2_common_functions

    if ! getent passwd ${DB2INSTANCE?} > /dev/null 2>&1; then
      echo "(*) Previous setup has not been detected. Creating the users... "
      create_users
    fi
    if ! create_instance; then
      exit 1
    fi
    start_db2
    cp /scripts/db2-createschema.sh /database/db2-createschema.sh 
    chmod +x /database/db2-createschema.sh
    su - $DB2INSTANCE -c "/database/db2-createschema.sh \"$DB2_SERVICE_NAME\" \"$DB2INSTANCE\" \"$DB2INST1_PASSWORD\" \"$DBNAME\""
  db2-createschema.sh: |
    #!/bin/sh
    DB2_SERVICE_NAME=$1
    DB2INSTANCE=$2
    DB2INST1_PASSWORD=$3
    DBNAME=$4
    echo "Configure schema for database \"$DBNAME\" on host \"$DB2_SERVICE_NAME\"."
    db2 "catalog tcpip node TRADERDB remote $DB2_SERVICE_NAME server 50000"
    db2 "catalog db $DBNAME as $DBNAME at node TRADERDB"
    db2 terminate
    db2 "activate database $DBNAME"
    db2 "connect to $DBNAME user $DB2INSTANCE using $DB2INST1_PASSWORD"
    sleep 2
    db2 -tvmf /scripts/stock-trader.sql
    echo "Database $DBNAME has been configured."
  stock-trader.sql: |
    CREATE TABLE Portfolio(owner VARCHAR(32) NOT NULL, total DOUBLE, loyalty VARCHAR(8), balance DOUBLE, commissions DOUBLE, free INTEGER, sentiment VARCHAR(16), PRIMARY KEY(owner));
    CREATE TABLE Stock(owner VARCHAR(32) NOT NULL, symbol VARCHAR(8) NOT NULL, shares INTEGER, price DOUBLE, total DOUBLE, dateQuoted DATE, commission DOUBLE, FOREIGN KEY (owner) REFERENCES Portfolio(owner) ON DELETE CASCADE, PRIMARY KEY(owner, symbol));
kind: ConfigMap
metadata:
  name: db2-createschema

